### ISSUE TITLE
Current version Known/unknown detection problem

### ISSUE THREAD

**Issue by beloware** [Noctem/Monocle#91] opened 2017-02-07 22:07 UTC
Running a current version for 4 hours on a brand new territory, did not take known, really low unknown points. 
After 4 hours was only 2 ! known points, and couple unknown.
Using older version same config, instantly gets the points and add it to known.
I put screen on discord channel.

Ubuntu LTS linux python 3.5 fresh instance all is the newest from git.

**Comment by baskettcase** [comment] 2017-02-07 22:23
I can confirm. Im getting the same exact behavior.

**Comment by thordurk91** [comment] 2017-02-08 02:19
I had to restart my scan.py when it hadn't found 100 unknowns after 1 day. Upon restart it found them all withing 20minutes.

Same case for a bigger instance where it had 5000 unknown pop in after 1 hour. When I had changed the migration time since I had a lot of wrong timers.

**Comment by Noctem** [comment] 2017-02-08 09:58
Silly oversight on my part with last-minute changes between seconds and milliseconds. Fixed in fa49058648aa2341b84e41b2d7ebc3db73dc4dc1.

**Closed by Noctem** 2017-02-08 09:58 UTC
